file = 
 _{ SOI
  ~ module
  ~ declaration*
  ~ EOI
  }

module = { "module" ~ Name ~ tuple ~ ";" }
Name = @{ ASCII_ALPHA_UPPER ~ ASCII_ALPHANUMERIC* }
tuple = { "(" ~ ")" | "(" ~ name ~ ("," ~ name)* ~ ")"}

declaration = { name ~ "=" ~ integer ~ ";" }
integer = @{ "0" | ("-"? ~ ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) }
name = @{ ASCII_ALPHA_LOWER ~ ASCII_ALPHANUMERIC* }

COMMENT = _{ "{-" ~ (!"-}" ~ ANY)* ~ "-}" }
WHITESPACE = _{ " " | "\t" | NEWLINE }
